name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:


jobs:
  ##################
  # Jobs with matrix
  ##################
  integration:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
          cache: 'npm'
      - name: install
        run: npm ci
      - name: install bitcoin
        run: |
          sudo apt-get install -y build-essential cmake pkgconf python3 libevent-dev libboost-dev libzmq3-dev libsqlite3-dev
          git clone --depth 1 --branch 2025_threadpool_http_server https://github.com/furszy/bitcoin-core
          cd bitcoin
          cmake -B build -DENABLE_WALLET=ON -DWITH_ZMQ=ON -DBUILD_GUI=OFF -DBUILD_BENCH=OFF -DBUILD_FUZZ_BINARY=OFF -DBUILD_GUI_TESTS=OFF -DBUILD_TESTS=OFF -DBUILD_UTIL=OFF -DBUILD_TX=OFF -DBUILD_WALLET_TOOL=OFF
          cmake --build build -j$(nproc)
          build/bin/bitcoind -regtest -txindex -zmqpubhashtx=tcp://127.0.0.1:30001 -zmqpubhashblock=tcp://127.0.0.1:30001 -rpcworkqueue=32 -daemon
          build/bin/bitcoin-cli -regtest -rpcwait createwallet ci
          build/bin/bitcoin-cli -regtest -rpcwait -generate 432
      - name: start regtest server
        run: |
          git clone https://github.com/bitcoinjs/regtest-server
          cd regtest-server
          npm install
          mkdir ~/regtest-data
          echo "satoshi" > ~/regtest-data/KEYS
          export RPCCOOKIE=~/.bitcoin/regtest/.cookie
          export KEYDB=~/regtest-data/KEYS
          export INDEXDB=~/regtest-data/db
          export ZMQ=tcp://127.0.0.1:30001
          export RPCCONCURRENT=32
          export RPC=http://localhost:18443
          export PORT=8080
          node index.js &
      - name: test
        run: |
          export APIPASS=satoshi
          export APIURL=http://127.0.0.1:8080/1
          npm run integration
