name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 'lts/*']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    services:
      regtest:
        image: junderw/bitcoinjs-regtest-server@sha256:5b69cf95d9edf6d5b3a00504665d6b3c382a6aa3728fe8ce897974c519061463
        ports:
          - 8080:8080
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
          cache: 'npm'
      - run: npm ci
      - run: APIURL=http://127.0.0.1:8080/1 npm run integration
